sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t geokoshy89/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true geokoshy89/docker-react npm run test
